### ISSUE TITLE
matplotlib no installed in the environment following documentation

### ISSUE THREAD

**Issue by franalcantara** [flexi-framework/relexi#2]
When creating the environment according to the documentation the following installations are done:

python3 -m pip install smartredis cmake tensorflow tf-agents pyyaml

However, matplotlib is also needed and therefore, it could be included:

python3 -m pip install smartredis cmake tensorflow tf-agents pyyaml matplotlib

**Comment by m-kurz** [comment]
Thanks, that's a good point. I'll add it to the environment packages.

**Comment by franalcantara** [comment]
I guess it was a matter of the matplotlib version, but I was getting an error in the file flexiEnvSmartSim.py inside the function _plot_spectra. LineWidth was not recognized because of the capital letters and linewidth had to be used. I think lowercase letters is more general and should work for all matplotlib versions

**Comment by m-kurz** [comment]
I just added the missing package and fixed the spelling of the `linewidth` parameter.
