### ISSUE TITLE
redis-server exe in SmartSim Config could not be used

### ISSUE THREAD

**Issue by franalcantara** [flexi-framework/relexi#3]
Hello, when executing the train.py file I get an error in the init_smartsim.py, when initializing the orchestrator:

`  # Initialize the orchestrator based on the orchestrator_type

  if orchestrator_type.casefold() == "local":

    db = Orchestrator(

            port=port,

            interface='lo'

            )`

The error is:

`File "/home/francisco/relexi/env_relexi/lib/python3.8/site-packages/smartsim/config.py", line 151, in redis_exe

raise SSConfigError(

smartsim.error.errors.SSConfigError: redis-server exe in SmartSim Config could not be used`

**Comment by m-kurz** [comment]
That sounds like a problem in SmartSim itself. Did you use the `smart` commandline tool to install SmartSim and its dependencies? Did you see any errors there? If the build process was successful, you should find the `redis-server` executable in the smartsim folder. Dependent on your version you should find it somewhere like `python3.8/site-packages/smartsim/_core/bin/redis-server`. You should be able to execute it and make sure that the rights to execute it are granted. If it is built properly and marked as executable, we have to dig deeper.

**Comment by franalcantara** [comment]
Effectively, the problem where the smartsim dependencies. After I installed git-lfs, following the steps of this link

[python3 ../../src/train.py prm.yaml](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage)

I can install smartsum properly.

I'm closing the issue
